# Generated by Django 4.2.16 on 2024-10-22 10:53

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Daly", email="daly54@email.com", document="22342586", phone="69632548").save()
    Student(name="Daly", email="daly54@email.com", document="22342586", phone="69632548").save()
    Student(name="Daly", email="daly54@email.com", document="22342586", phone="69632548").save()
    Student(name="Daly", email="daly54@email.com", document="22342586", phone="69632548").save()
class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]